# docker-compose -f docker-compose.withoutsql.yml up --build

services:
  product-service:
    build:
      context: ./src/ProductService/ProductService.API
      dockerfile: Dockerfile
    ports:
      - "8010:8080"
    volumes:
      - ./src/ProductService:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=ProductServiceDb;User=sa;Password=p@ssw0rd;TrustServerCertificate=true;Encrypt=false;"
    command:
      ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--project", "ProductService.API/ProductService.API.csproj", "--launch-profile", "Docker"]
  
  customer-service:
    build:
      context: ./src/CustomerService/CustomerService.API
      dockerfile: Dockerfile
    ports:
      - "8020:8080"
    volumes:
      - ./src/CustomerService:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=CustomerServiceDb;User=sa;Password=p@ssw0rd;TrustServerCertificate=true;Encrypt=false;"
    command:
      ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--project", "CustomerService.API/CustomerService.API.csproj", "--launch-profile", "Docker"]

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./ApiGateway:/app
    depends_on:
      - product-service
      - customer-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ReverseProxy__Clusters__productCluster__Destinations__productAPI__Address=http://product-service:8080/"
      - "ReverseProxy__Clusters__customerCluster__Destinations__customerAPI__Address=http://customer-service:8080/"
    command:
      ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--project", "ApiGateway.csproj", "--launch-profile", "Docker"]

  auth-service:
    build:
      context: ./AuthService.API
      dockerfile: Dockerfile
    ports:
      - "8005:8080"
    volumes:
      - ./AuthService.API:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=M2QzMy00Y2MwLTg3NDEtYjM4OGUxMTkxNmQxI
      - Jwt__ExpiryMinutes=60
    command:
      ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--project", "AuthService.API.csproj", "--launch-profile", "Docker"]
