services:
  product-service:
    build:
      context: ./src/ProductService
      dockerfile: ProductService.API/Dockerfile.production
    ports:
      - "8010:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductServiceDb;User=sa;Password=p@ssw0rd;TrustServerCertificate=true;Encrypt=false;
    command:
      ["sh", "-c", "./ProductService.API/wait-for-sql.sh sqlserver dotnet ProductService.API.dll"]

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile.production
    ports:
      - "8000:8080"
    depends_on:
      - product-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "p@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
