# docker-compose up OR docker-compose up --build

services:
  product-service:
    build:
      context: ./src/ProductService
      dockerfile: ProductService.API/Dockerfile
    ports:
      - "8010:8080"
    depends_on:
      - sql-server
    volumes:
      - ./src/ProductService:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=sql-server;Database=ProductServiceDb;User=sa;Password=p@ssw0rd;TrustServerCertificate=true;Encrypt=false;"
    command:
      ["./ProductService.API/wait-for-it.sh", "sql-server:1433", "--", "dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--project", "ProductService.API/ProductService.API.csproj", "--launch-profile", "Docker"]
  
  customer-service:
    build:
      context: ./src/CustomerService
      dockerfile: CustomerService.API/Dockerfile
    ports:
      - "8020:8080"
    depends_on:
      - sql-server
    volumes:
      - ./src/CustomerService:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=sql-server;Database=CustomerServiceDb;User=sa;Password=p@ssw0rd;TrustServerCertificate=true;Encrypt=false;"
    command:
      ["./CustomerService.API/wait-for-it.sh", "sql-server:1433", "--", "dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--project", "CustomerService.API/CustomerService.API.csproj", "--launch-profile", "Docker"]

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./ApiGateway:/app
    depends_on:
      - product-service
      - customer-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ReverseProxy__Clusters__productCluster__Destinations__productAPI__Address=http://product-service:8080/"
      - "ReverseProxy__Clusters__customerCluster__Destinations__customerAPI__Address=http://customer-service:8080/"
    command:
      ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--project", "ApiGateway.csproj", "--launch-profile", "Docker"]

  auth-service:
    build:
      context: ./AuthService.API
      dockerfile: Dockerfile
    ports:
      - "8005:8080"
    volumes:
      - ./AuthService.API:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=M2QzMy00Y2MwLTg3NDEtYjM4OGUxMTkxNmQxI
      - Jwt__ExpiryMinutes=60
    command:
      ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--project", "AuthService.API.csproj", "--launch-profile", "Docker"]

  sql-server:
    image: mcr.microsoft.com/azure-sql-edge     #mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      MSSQL_SA_PASSWORD: "p@ssw0rd"             #SA_PASSWORD: "p@ssw0rd"
      ACCEPT_EULA: "1"                          #ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" #set the host port to something else to be able to access it from the host (as the host sql server is already running on port 1433)
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
